version: "3"
services:
  todo:
    ports:
      - 5000:5000
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://trihm:@db:5432/training_db?sslmode=disable
      ADDRESS_DATABASE: address.csv
      SERVER_SECRET: secret

  db:
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: training_db
      POSTGRES_USER: trihm
    image: postgres:11.2-alpine
