version: "3"
services:
  todo:
    ports:
      - 5000:5000
    build: .
    restart: always
    depends_on:
      - postgresDB
    environment:
      ORACLE_URL: oracle://khanhnv:2305@exax7-scan.vnpthcm.vn:1521/SGN
      DATABASE_URL: postgres://trihm:@postgresDB:5432/training_db?sslmode=disable
      ADDRESS_DATABASE: address.csv
      SERVER_SECRET: secret

  postgresDB:
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: training_db
      POSTGRES_USER: trihm
    image: postgres:11.2-alpine
